backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Publish mode option (editorial workflow)
publish_mode: editorial_workflow

# Media folder where uploaded images will be stored in your repo
media_folder: "public/images/uploads" 
# Public path to media
public_folder: "/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/data/blog-posts" # Updated path to match your project structure
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "News", value: "News" }
          - { label: "Technology", value: "Technology" }
          - { label: "Trailers", value: "Trailers" }
          - { label: "Deals", value: "Deals" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        default: []
      - {label: "Body", name: "body", widget: "markdown"}