backend:
  name: github
  repo: Sloane-J/astro-blog
  branch: main

media_folder: "public/assets/blog"  # Where images are stored in the repo
public_folder: "/assets/blog"  # URL path for accessing images

collections:
  - name: "blog"
    label: "Astro Blog"
    folder: "src/pages/blog"  # Astro Content Collection Folder
    create: true
    slug: "{{slug}}"
    extension: md  # Ensure Markdown files are used
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Featured Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Tech", "Lifestyle", "News"]
      - label: "Body"
        name: "body"
        widget: "markdown"
