backend:
  name: git-gateway
  branch: main  # Branch to update

media_folder: "public/assets/blog"  # Where images are stored in the repo
public_folder: "/assets/blog"  # URL path for accessing images

publish_mode: editorial_workflow  # Enables draft and preview functionality

collections:
  - name: "blog"
    label: "Astro Blog"
    folder: "src/data/blog-posts"  # Ensure this matches your blog's location
    create: true  # Allow new posts
    slug: "{{slug}}"  # Match Astro's dynamic routing
    extension: "md"  # Ensure Markdown files
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogLayout.astro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Category", name: "category", widget: "select", options: ["News", "Technology", "Trailers", "Deals"], default: "News" }
      - { label: "Body", name: "body", widget: "markdown" }
